apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: default
type: Opaque
data:
  # Base64 encoded values
  postgres-user: "petclinic" 
  postgres-password: "petclinic" 
  postgres-db: "petclinic" 
  # postgres-user: cGV0Y2xpbmljaw==
  # postgres-password: cGV0Y2xpbmljaw==
  # postgres-db: cGV0Y2xpbmljaw==